services:
  api-server:
    build:
      context: ./api-server
    depends_on:
      - card-database
      - user-database
    environment:
      NODE_ENV: production
      USER_MYSQL_HOST: user-database
      USER_MYSQL_USER: root
      USER_MYSQL_PASSWORD: secret
      USER_MYSQL_DB: users
      CARD_MYSQL_HOST: card-database
      CARD_MYSQL_USER: root
      CARD_MYSQL_PASSWORD: secret
      CARD_MYSQL_DB: cards
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./api-server/package.json
          action: rebuild
        - path: ./api-server
          target: /usr/src/app
          action: sync

  card-database:
    image: mysql:8.0
    volumes:
      - card-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cards

  user-database:
    image: mysql:8.0
    volumes:
      - user-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: users

  reminder-producer:
    build:
      context: ./reminder-producer
    depends_on:
      - card-database
      - user-database
      - rabbitmq
    environment:
      NODE_ENV: production
      USER_MYSQL_HOST: user-database
      USER_MYSQL_USER: root
      USER_MYSQL_PASSWORD: secret
      USER_MYSQL_DB: users
      CARD_MYSQL_HOST: card-database
      CARD_MYSQL_USER: root
      CARD_MYSQL_PASSWORD: secret
      CARD_MYSQL_DB: cards
      RABBITMQ_HOST: rabbitmq
      QUEUE_NAME: "notifications"
    develop:
      watch:
        - path: ./reminder-producer/package.json
          action: rebuild
        - path: ./reminder-producer
          target: /usr/src/app
          action: sync

  reminder-consumer:
    build:
      context: ./reminder-consumer
    depends_on:
      - card-database
      - user-database
      - rabbitmq
    environment:
      NODE_ENV: production
      USER_MYSQL_HOST: user-database
      USER_MYSQL_USER: root
      USER_MYSQL_PASSWORD: secret
      USER_MYSQL_DB: users
      CARD_MYSQL_HOST: card-database
      CARD_MYSQL_USER: root
      CARD_MYSQL_PASSWORD: secret
      CARD_MYSQL_DB: cards
      RABBITMQ_HOST: rabbitmq
      QUEUE_NAME: "notifications"
    develop:
      watch:
        - path: ./reminder-consumer/package.json
          action: rebuild
        - path: ./reminder-consumer
          target: /usr/src/app
          action: sync

  client-webhook:
    build:
      context: ./client-webhook
    environment:
      NODE_ENV: production
    ports:
      - 3001:3000
    develop:
      watch:
        - path: ./client-webhook/package.json
          action: rebuild
        - path: ./client-webhook
          target: /usr/src/app
          action: sync

  rabbitmq:
    image: rabbitmq:3.13-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  card-data:
  user-data:
  rabbitmq-data:
  rabbitmq-log:
