services:
  api-server:
    build:
      context: ./api-server
    depends_on:
      - card-database
      - user-database
    environment:
      NODE_ENV: production
      USER_MYSQL_HOST: user-database
      USER_MYSQL_USER: root
      USER_MYSQL_PASSWORD: secret
      USER_MYSQL_DB: users
      CARD_MYSQL_HOST: card-database
      CARD_MYSQL_USER: root
      CARD_MYSQL_PASSWORD: secret
      CARD_MYSQL_DB: cards
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./api-server/package.json
          action: rebuild
        - path: ./api-server
          target: /usr/src/app
          action: sync

  card-database:
    image: mysql:8.0
    volumes:
      - card-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cards

  user-database:
    image: mysql:8.0
    volumes:
      - user-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: users

volumes:
  card-data:
  user-data:
